Add small test for v15 backwards compatibility
sourcegraph/zoekt pull request #23
Opened 2019-08-21 12:47 UTC by kzh

2019-08-21 13:20 UTC, keegancsmith requested changes
These files are huge. Can we instead just index a very simple repo containing one file?

```
$ du -h test-index/
4.7M    test-index/
```

2019-08-21 13:20 UTC, keegancsmith commented on read_test.go
> +		shard, err := loadShard("test-index/" + tc.file)
In go we call test data directories like this `testdata`.

2019-08-27 11:31 UTC, keegancsmith commented
@kzh ping?

2019-08-28 15:06 UTC, kzh commented
Hey @keegancsmith, I updated the test to make use of a golden file for validation. Sorry, I got a little sidetracked with the performance testing on symbol search.

2019-08-28 19:39 UTC, keegancsmith approved these changes
Two changes before landing:

- Can you include a way to update the golden file. Normally one adds a `-update` flag. EG see how we do it in the sourcegraph repo or the golang repo https://sourcegraph.com/search?q=r:%5Egithub.com/%28sourcegraph/sourcegraph%7Cgolang/go%29%24+flag%5C.%5BA-Z%5D+%28golden%7Cupdate%29+f:test.go
- Marshal the golden files with indentation. Will make it easier to review changes to them.

2019-08-28 19:39 UTC, keegancsmith commented on read_test.go
> +	if err := json.NewDecoder(f).Decode(&want); err != nil {
don't we want a different golden file per shard? ie I'd suspect we should test shards without symbols.

2019-08-28 19:39 UTC, keegancsmith commented on read_test.go
> +	f, err := os.Open(golden)
You can avoid the file you need to close via something like

```go
if buf, err := ioutil.ReadFile(golden); err != nil {
  t.Fatal(err)
} else if err = json.Unmarshal(buf, &want); err != nil {
  t.Fatal(err)
}
```

2019-08-29 07:27 UTC, keegancsmith approved these changes

2019-08-29 07:40 UTC, merged