Document how to run ctags with custom settings
sourcegraph/zoekt pull request #268
Opened 2022-02-09 20:08 UTC by kisabaka

Zoekt supports starting a custom `ctags` binary which can be useful when the default settings cause `ctags` to fail (e.g when a language isn't available on the host system)

2022-02-09 20:49 UTC, kisabaka commented
@keegancsmith  improving the ctags docs to get past issues like this: https://github.com/sourcegraph/go-ctags/issues/6

2022-02-10 07:05 UTC, keegancsmith requested changes
These are quite detailed instructions. We already mention the name of the package in the current description. I think it would be better for us to just implement the linked issue. But we should also bump the version of ctags we use to be honest and adjust the language list accordingly :) I'll do the latter today.

2022-02-10 09:09 UTC, kisabaka commented
That sounds good to me! I ran into the issue with this version of ctags:
```
$ universal-ctags --version
Universal Ctags 0.0.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Jan  6 2019, 23:23:29
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml
```

2025-01-24 23:17 UTC, jtibshirani commented
Closing this now that https://github.com/sourcegraph/go-ctags/issues/6 is resolved. Feel free to reopen or suggest a different docs change!

2025-01-24 23:17 UTC, closed without merging