zoekt-mirror-gerrit: fix issue when anonymous http is disabled on Gerrit
sourcegraph/zoekt pull request #281
Opened 2022-02-16 12:45 UTC by df11

The previous implementation would always end up selecting "anonymous http" scheme.
When this option is disabled on Gerrit it can't work.
So the change selects the first available scheme in Gerrit configuration instead.

2022-02-28 14:18 UTC, stefanhengl requested changes
nice catch!

2022-02-28 14:18 UTC, stefanhengl commented on cmd/zoekt-mirror-gerrit/main.go
> +		}
```suggestion
                if shemeInfo, ok := info.Download.Schemes[s]; ok {
                    projectURL = schemeInfo.URL
                    break
                }
```

2022-03-02 09:34 UTC, df11 commented
Thanks for your suggestion. I added it to the PR.

2022-03-03 11:04 UTC, stefanhengl approved these changes

2022-03-04 12:56 UTC, merged