fetch options from server and pass them through to index command
sourcegraph/zoekt pull request #3
Opened 2019-04-10 01:26 UTC by ijsnow

> IMPORTANT: Do not merge until https://gerrit-review.googlesource.com/c/zoekt/+/220077 as accepted and merged.

This PR is part of the solution for https://github.com/sourcegraph/sourcegraph/issues/1624. We are adding a configuration option called "search.largeFiles" which is a list of glob patterns. Any files matching the patterns in the list will be indexed and searched regardless of the size.

This PR fetches this option from Sourcegraph and passes it through as a new option to the zoekt index command.

2019-04-11 18:28 UTC, ijt commented on cmd/zoekt-sourcegraph-indexserver/main.go
> +func getIndexOptions(root *url.URL) (*IndexOptions, error) {
Can you add a test for it?

2019-04-12 20:08 UTC, keegancsmith requested changes

2019-04-12 20:08 UTC, keegancsmith commented on cmd/zoekt-sourcegraph-indexserver/main.go
> +		opts.toArgs(),
I don't think this works. Each argument needs to be its own string. You probably need to make all these args below a slice, then do something like `args = append(args, opts.toArgs()...)`

2019-04-12 20:08 UTC, keegancsmith commented on cmd/zoekt-sourcegraph-indexserver/main_test.go
> +		w.Write([]byte(`{"LargeFiles": ["test"]}`))
can you make your test more than one arg and for it to test toArgs

2019-04-12 20:08 UTC, keegancsmith commented on cmd/zoekt-sourcegraph-indexserver/main.go
> +		f += "-large_file " + o.LargeFiles[i]
you shoudl be building a `[]string` where arg is two elements of the string or a single string combined with `"-large_file=" + o.LargeFiles[i]`

2019-04-12 20:08 UTC, keegancsmith commented on cmd/zoekt-sourcegraph-indexserver/main.go
> +	for i := range o.LargeFiles {
```suggestion
	for _, a := range o.LargeFiles {
```

2019-04-13 00:07 UTC, ijsnow commented
@keegancsmith is it ok to pass `-incremental=false` when running `Server.Index()` from the debug panel?
 
I am adding logic to ensure that a given repository's index is updated if the index options (large files) has been changed since the last time it was indexed. This is easy when just updating the code in `Server.Run()`. I just need to save the options in the queue and then fetch the updated options inside the `Server.Index()` function and pass `-incremental=false` if the options are not equal. 

This becomes more difficult in `Server.ServeHTTP()`. I would need to either add the queue to the server struct or add some more complicated logic/duplicate storage of the repo name and the options used to be able to keep these in sync.

2019-04-18 10:57 UTC, keegancsmith approved these changes

2019-04-18 10:58 UTC, keegancsmith commented
> @keegancsmith is it ok to pass -incremental=false when running Server.Index() from the debug panel? See a5b4601 for logic.

An update for others. We chatted about this a while ago over slack. The solution that was decided on was to make `-incremental=true` detect if it needs to reindex in zoekt based on large file globs changing.

2019-04-18 17:16 UTC, merged

2019-04-30 08:51 UTC, keegancsmith commented on cmd/zoekt-sourcegraph-indexserver/main.go
> +		fmt.Println(resp.StatusCode)
@ijsnow accidental debug log?