add DISABLE_MMAP flag which allows for disabling usage of mmap on Linux
sourcegraph/zoekt pull request #37
Opened 2020-03-11 03:16 UTC by slimsag

This allows disabling the usage of mmap on Linux. In some deployments of Zoekt
we have seen this mmap usage lead to large variance in the response time of
Zoekt after specific indexes are not used for a few minutes and get paged out
of the OS page cache. e.g. the page cache gets invalidated, someone runs a
search query that relies on the mmap'd index, and the OS then must load a
substantial amount of data from disk resulting in a response time of e.g. 10s
instead of the regular 0.15s.

Using `DISABLE_MMAP=true` works around this problem by ensuring the index
files are always loaded into memory. Another option considered would've
been to use `madvise`, but this seemed more complex to figure out the exact
semantics of (after all, it is just advise for the kernel and not guaranteed)
especially in the context of zoekt running in e.g. Alpine linux with an arbitrary
host linux kernel.

The implementation is simple because Zoekt already supports loading index files
into memory on non-linux OSs, this just makes it optional on Linux (off by default)
where the behavior previously would've been to always use mmap.

Helps https://github.com/sourcegraph/customer/issues/37

2020-03-11 03:17 UTC, slimsag commented
@keegancsmith do you think this is worth upstreaming? if yes, perhaps you already have Gerrit set up / familiar and could submit this on my behalf once it LGTY?

2020-03-11 11:29 UTC, keegancsmith requested changes
This doesn't load all the content into memory. Rather it just uses a SeekReader (ie uses ReadAt calls). This would likely suffer from the same issues mmap does since it shares the same underlying FS page cache. It would actually be slower, since we would have to do a syscall to read a part of a file.

We could implement a `indexFileInMemory` struct which reads the whole file into a `[]byte`. However, we would use significantly more memory since it would duplicate data that we load into in-memory indexes (notably the trigram index). I'll look into implementing just storing the contents in memory, but the initial stopgap solution of indexFileInMemory would likely help us as well and is rather straighftforward to implement.

2020-03-11 22:24 UTC, slimsag commented on indexfile_linux.go
> +	}
We could copy this logic to indexfile_nolinux too, now, I guess -- but maybe that doesn't matter.

2020-03-11 22:25 UTC, slimsag commented
Nice, thank you for catching that and pushing the change @keegancsmith ! LGTM

2020-03-12 21:41 UTC, slimsag commented
Closing in favor of https://github.com/sourcegraph/zoekt/pull/38

2020-03-12 21:41 UTC, closed without merging